import { Product } from "./definitions";

export const featuredProducts = [
    {
        image: "/assets/product-headphones.jpg",
        title: "Premium Wireless Headphones",
        price: 199.99,
        originalPrice: 299.99,
        badge: "sale" as const,
    },
    {
        image: "/assets/product-backpack.jpg",
        title: "Leather Travel Backpack",
        price: 149.99,
        badge: "new" as const,
    },
    {
        image: "/assets/product-watch.jpg",
        title: "Classic Minimalist Watch",
        price: 249.99,
        originalPrice: 349.99,
        badge: "sale" as const,
    },
    {
        image: "/assets/product-sunglasses.jpg",
        title: "Designer Sunglasses",
        price: 89.99,
        badge: "featured" as const,
    },
];

export const discountedProducts = [
    {
        image: "/assets/product-phone.jpg",
        title: "Latest Smartphone Pro",
        price: 799.99,
        originalPrice: 999.99,
        badge: "sale" as const,
    },
    {
        image: "/assets/product-laptop.jpg",
        title: "Ultra-Slim Laptop",
        price: 1299.99,
        originalPrice: 1599.99,
        badge: "sale" as const,
    },
];

export const categories = [
    {
        title: "Electronics",
        itemCount: 245,
        icon: `<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-smartphone-icon lucide-smartphone"><rect width="14" height="20" x="5" y="2" rx="2" ry="2"/><path d="M12 18h.01"/></svg>`,
    },
    {
        title: "Fashion",
        itemCount: 189,
        icon: `<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-sparkles-icon lucide-sparkles"><path d="M11.017 2.814a1 1 0 0 1 1.966 0l1.051 5.558a2 2 0 0 0 1.594 1.594l5.558 1.051a1 1 0 0 1 0 1.966l-5.558 1.051a2 2 0 0 0-1.594 1.594l-1.051 5.558a1 1 0 0 1-1.966 0l-1.051-5.558a2 2 0 0 0-1.594-1.594l-5.558-1.051a1 1 0 0 1 0-1.966l5.558-1.051a2 2 0 0 0 1.594-1.594z"/><path d="M20 2v4"/><path d="M22 4h-4"/><circle cx="4" cy="20" r="2"/></svg>`,
    },
    {
        title: "Accessories",
        itemCount: 324,
        icon: `<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-watch-icon lucide-watch"><path d="M12 10v2.2l1.6 1"/><path d="m16.13 7.66-.81-4.05a2 2 0 0 0-2-1.61h-2.68a2 2 0 0 0-2 1.61l-.78 4.05"/><path d="m7.88 16.36.8 4a2 2 0 0 0 2 1.61h2.72a2 2 0 0 0 2-1.61l.81-4.05"/><circle cx="12" cy="12" r="6"/></svg>`,
    },
    {
        title: "Audio",
        itemCount: 156,
        icon: `<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-headphones-icon lucide-headphones"><path d="M3 14h3a2 2 0 0 1 2 2v3a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-7a9 9 0 0 1 18 0v7a2 2 0 0 1-2 2h-1a2 2 0 0 1-2-2v-3a2 2 0 0 1 2-2h3"/></svg>`,
    },
    {
        title: "Bags",
        itemCount: 98,
        icon: `<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-backpack-icon lucide-backpack"><path d="M4 10a4 4 0 0 1 4-4h8a4 4 0 0 1 4 4v10a2 2 0 0 1-2 2H6a2 2 0 0 1-2-2z"/><path d="M8 10h8"/><path d="M8 18h8"/><path d="M8 22v-6a2 2 0 0 1 2-2h4a2 2 0 0 1 2 2v6"/><path d="M9 6V4a2 2 0 0 1 2-2h2a2 2 0 0 1 2 2v2"/></svg>`,
    },
    {
        title: "Tech",
        itemCount: 412,
        icon: `<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-laptop-icon lucide-laptop"><path d="M18 5a2 2 0 0 1 2 2v8.526a2 2 0 0 0 .212.897l1.068 2.127a1 1 0 0 1-.9 1.45H3.62a1 1 0 0 1-.9-1.45l1.068-2.127A2 2 0 0 0 4 15.526V7a2 2 0 0 1 2-2z"/><path d="M20.054 15.987H3.946"/></svg>`,
    },
];

export const products: Product[] = [
    {
        id: "prod-01",
        image: "/assets/product-headphones.jpg",
        title: "Premium Wireless Headphones",
        price: 199.99,
        originalPrice: 299.99,
        category: "Audio",
        size: ["One Size"],
        badge: "sale",
        dateAdded: new Date("2025-01-15"),
    },
    {
        id: "prod-02",
        image: "/assets/product-backpack.jpg",
        title: "Leather Travel Backpack",
        price: 149.99,
        category: "Bags",
        size: ["Medium", "Large"],
        badge: "new",
        dateAdded: new Date("2025-02-01"),
    },
    {
        id: "prod-03",
        image: "/assets/product-watch.jpg",
        title: "Classic Minimalist Watch",
        price: 249.99,
        originalPrice: 349.99,
        category: "Accessories",
        size: ["Small", "Medium", "Large"],
        badge: "sale",
        dateAdded: new Date("2025-01-20"),
    },
    {
        id: "prod-04",
        image: "/assets/product-sunglasses.jpg",
        title: "Designer Sunglasses",
        price: 89.99,
        category: "Fashion",
        size: ["One Size"],
        badge: "featured",
        dateAdded: new Date("2025-01-25"),
    },
    {
        id: "prod-05",
        image: "/assets/product-phone.jpg",
        title: "Latest Smartphone Pro",
        price: 799.99,
        originalPrice: 999.99,
        category: "Electronics",
        size: ["128GB", "256GB", "512GB"],
        badge: "sale",
        dateAdded: new Date("2025-01-10"),
    },
    {
        id: "prod-06",
        image: "/assets/product-laptop.jpg",
        title: "Ultra-Slim Laptop",
        price: 1299.99,
        originalPrice: 1599.99,
        category: "Tech",
        size: ["13 inch", "15 inch"],
        badge: "sale",
        dateAdded: new Date("2025-01-18"),
    },
    {
        id: "prod-07",
        image: "/assets/product-headphones.jpg",
        title: "Headphones Pro",
        price: 219.99,
        originalPrice: 319.99,
        category: "Audio",
        size: ["One Size"],
        badge: "sale",
        dateAdded: new Date("2025-02-15"),
    },
    {
        id: "prod-08",
        image: "/assets/product-backpack.jpg",
        title: "Urban Backpack",
        price: 120.0,
        category: "Bags",
        size: ["Medium"],
        badge: "new",
        dateAdded: new Date("2025-03-01"),
    },
    {
        id: "prod-09",
        image: "/assets/product-watch.jpg",
        title: "Luxury Steel Watch",
        price: 550.0,
        originalPrice: 650.0,
        category: "Accessories",
        size: ["Medium"],
        badge: "sale",
        dateAdded: new Date("2025-02-20"),
    },
    {
        id: "prod-10",
        image: "/assets/product-sunglasses.jpg",
        title: "Retro Sunglasses",
        price: 75.0,
        category: "Fashion",
        size: ["One Size"],
        badge: "featured",
        dateAdded: new Date("2025-02-25"),
    },
    {
        id: "prod-11",
        image: "/assets/product-phone.jpg",
        title: "Compact Smartphone",
        price: 599.99,
        category: "Electronics",
        size: ["128GB"],
        badge: "new",
        dateAdded: new Date("2025-03-10"),
    },
    {
        id: "prod-12",
        image: "/assets/product-laptop.jpg",
        title: "Gaming Laptop",
        price: 1899.99,
        originalPrice: 2099.99,
        category: "Tech",
        size: ["16 inch"],
        badge: "sale",
        dateAdded: new Date("2025-03-18"),
    },
    {
        id: "prod-13",
        image: "/assets/product-headphones.jpg",
        title: "Noise-Cancelling Headphones",
        price: 249.99,
        category: "Audio",
        size: ["One Size"],
        badge: "new",
        dateAdded: new Date("2025-04-01"),
    },
    {
        id: "prod-14",
        image: "/assets/product-backpack.jpg",
        title: "Waterproof Hiking Backpack",
        price: 180.0,
        category: "Bags",
        size: ["Large"],
        badge: "featured",
        dateAdded: new Date("2025-04-05"),
    },
    {
        id: "prod-15",
        image: "/assets/product-watch.jpg",
        title: "Smart Sports Watch",
        price: 350.0,
        originalPrice: 400.0,
        category: "Accessories",
        size: ["One Size"],
        badge: "sale",
        dateAdded: new Date("2025-04-10"),
    },
    {
        id: "prod-16",
        image: "/assets/product-sunglasses.jpg",
        title: "Polarized Aviator Sunglasses",
        price: 110.0,
        category: "Fashion",
        size: ["One Size"],
        badge: "new",
        dateAdded: new Date("2025-04-15"),
    },
    {
        id: "prod-17",
        image: "/assets/product-phone.jpg",
        title: "Budget-Friendly Smartphone",
        price: 299.99,
        category: "Electronics",
        size: ["64GB"],
        badge: "featured",
        dateAdded: new Date("2025-04-20"),
    },
    {
        id: "prod-18",
        image: "/assets/product-laptop.jpg",
        title: "2-in-1 Touchscreen Laptop",
        price: 1400.0,
        originalPrice: 1600.0,
        category: "Tech",
        size: ["14 inch"],
        badge: "sale",
        dateAdded: new Date("2025-04-25"),
    },
    {
        id: "prod-19",
        image: "/assets/product-headphones.jpg",
        title: "Wireless Earbuds",
        price: 89.99,
        category: "Audio",
        size: ["One Size"],
        badge: "new",
        dateAdded: new Date("2025-05-01"),
    },
    {
        id: "prod-20",
        image: "/assets/product-backpack.jpg",
        title: "Laptop Backpack",
        price: 95.0,
        category: "Bags",
        size: ["Medium"],
        badge: "sale",
        dateAdded: new Date("2025-05-05"),
    },
    {
        id: "prod-21",
        image: "/assets/product-watch.jpg",
        title: "Casual Leather Watch",
        price: 120.0,
        category: "Accessories",
        size: ["Medium"],
        badge: "new",
        dateAdded: new Date("2025-05-10"),
    },
    {
        id: "prod-22",
        image: "/assets/product-sunglasses.jpg",
        title: "Sporty Sunglasses",
        price: 65.0,
        category: "Fashion",
        size: ["One Size"],
        badge: "featured",
        dateAdded: new Date("2025-05-15"),
    },
    {
        id: "prod-23",
        image: "/assets/product-phone.jpg",
        title: "Flagship Smartphone",
        price: 1099.99,
        originalPrice: 1299.99,
        category: "Electronics",
        size: ["512GB", "1TB"],
        badge: "sale",
        dateAdded: new Date("2025-05-20"),
    },
    {
        id: "prod-24",
        image: "/assets/product-laptop.jpg",
        title: "Desktop Replacement Laptop",
        price: 2199.99,
        category: "Tech",
        size: ["17 inch"],
        badge: "new",
        dateAdded: new Date("2025-05-25"),
    },
];
